spring.application.name:
    mybatis-plus
mybatis:
    configuration:
        map-underscore-to-camel-case: true
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true
        auto-mapping-behavior: full
        # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        mapper-locations: classpath*:/**/mapper/**/*.xml
    type-aliases-package: com.tfq.dao
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/hm-item?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123000
server:
    port: 8080
